// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

// Initialize Supabase client.
// Ensure localStorage is only accessed in a browser environment.
// For SSR, you might need a different storage solution or ensure this client is only used client-side.
// Since this file is marked 'use client', we can safely assume it will primarily run on the client,
// but Next.js might still attempt to evaluate it during build/SSR.
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // Conditionally use localStorage only if window is defined (i.e., in a browser environment)
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
